//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskId { get; set; }
        public int userId { get; set; }
        public string taskDesc { get; set; }
        public System.DateTime creation_dt { get; set; }
        public Nullable<System.DateTime> modified_dt { get; set; }
        public string status { get; set; }
        public string taskName { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
